Update action to run on node20
dblock/create-a-github-issue pull request #123
Opened 2024-04-24 17:11 UTC by pkwarren

Fixes #121.

2024-04-24 17:13 UTC, pkwarren commented on tsconfig.json
> -    "esModuleInterop": true
This is set to true in the base config: https://github.com/tsconfig/bases/blob/be6b3bb160889347b8614e8d18e1e88c40f8ecc9/bases/node20.json#L12

2024-04-25 00:55 UTC, dblock approved these changes
Let's bump the version.

2024-04-25 00:55 UTC, dblock commented on CHANGELOG.md
> -* Your contribution here.
Put back that line pls.

2024-04-25 00:55 UTC, dblock commented on CHANGELOG.md
>  ### 3.1.2 (Next)
Lets bump the version to 3.2.0 since we have a new "feature" as part of this PR.

2024-04-25 00:56 UTC, dblock requested changes
We also should bump it in CI, shouldn't we?

https://github.com/dblock/create-a-github-issue/blob/main/.github/workflows/ci.yml#L15

2024-04-25 13:22 UTC, dblock requested changes
The version increment in package.json/lock (https://github.com/dblock/create-a-github-issue/blob/68381210a25b5c64fe67add12d8f4713230ce53b/package.json#L3), too, please?

2024-04-25 13:52 UTC, merged

2024-04-25 13:52 UTC, dblock commented
Thanks for contributing!

2024-04-25 19:18 UTC, dblock commented
@pkwarren If you're looking for more work, finishing https://github.com/dblock/create-a-github-issue/issues/110 would be grand!